modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"
logoFile="modernui_logo.png"

[[mods]]
    modId="modernui"
    version="${version}"
    displayName="Modern UI"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    credits="BloCamLimb"
    description='''
    Creates fancy UI with better menu, fonts, animations, optimization and many utility functions, also a gui library for other mods.
    '''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2, 1.16)"
    ordering="NONE"
    side="BOTH"
