modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"
logoFile="modernui_logo.png"

[[mods]]
    modId="modernui"
    version="${version}"
    displayName="Modern UI"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    credits="BloCamLimb"
    description='''
    Modern UI gives you a brand-new system to easily create modernized and highly flexible UI in Minecraft.
    '''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.57,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1, 1.17)"
    ordering="NONE"
    side="BOTH"
