modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"

[[mods]]
modId="modernui"
version="${file.jarVersion}"
displayName="Modern UI"
displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
authors="BloCamLimb (Icyllis Milica)"
description='''Modern Style GUI/UI Library.'''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2, 1.16)"
    ordering="NONE"
    side="BOTH"
