modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"

[[mods]]
    modId="modernuifont"
    version="${version}"
    displayName="Modern UI - Font"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    credits="BloCamLimb"
    description='''
    Modern UI gives you a brand-new system to easily create modernized and highly flexible UI in Minecraft.
    '''

[[dependencies.modernuifont]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.57,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernuifont]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1, 1.17)"
    ordering="NONE"
    side="BOTH"
