modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"
logoFile= "modernui_logo.png"
license="All Rights Reserved"

[[mods]]
    modId="modernui"
    version="${version}"
    displayName="Modern UI"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    credits="BloCamLimb, et al., The Android Open Source Project"
    description='''
    Modern UI is a UI engine for desktop application development, which is mainly used for Minecraft and provides a wealth of functionality.
    It has broad compatibility, a high performance render engine, a text engine with good internationalization ability and so on.
    '''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17)"
    ordering="NONE"
    side="BOTH"
