modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"
logoFile= "modernui_logo.png"
license="Multi-licensing, see https://github.com/BloCamLimb/ModernUI for details"

[[mods]]
    modId="modernui"
    version="${version}"
    displayName="Modern UI"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    credits="BloCamLimb, et al., The Android Open Source Project"
    description='''
    Modern UI is a framework for standlone desktop application development, which provides a wealth of functionality and broad compatibility with good performance.
    '''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"
